# Site settings
title: Xccelerate Me
email: your-email@domain.com
description: "Startpage with useful data science links found during Xccelerate Oct 2018 full-time data science cohort"
baseurl: "/xccelerate_startpage/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
background_url: 'https://source.unsplash.com/collection/3491181'

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, README.md]

sass:
  style: compressed
